name: test
on: [push, pull_request]
 
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: pcov
 
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
 
      - name: Run tests
        run: vendor/bin/pest --coverage --min=100

      - name: Codecov
        uses: codecov/codecov-action@v3
